// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Test_Basic

#include "ui.h"

void ui_comp_Chart1_create_hook(lv_obj_t * comp)
{
}
