// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: BME_280_Chart

#include "ui.h"

// COMPONENT Chart1

lv_obj_t * ui_Chart1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Chart1;
    cui_Chart1 = lv_chart_create(comp_parent);
    lv_obj_set_width(cui_Chart1, 200);
    lv_obj_set_height(cui_Chart1, 100);
    lv_obj_set_align(cui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(cui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(cui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(cui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(cui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * cui_Chart1_series_1 = lv_chart_add_series(cui_Chart1, lv_color_hex(0x808080),
                                                                  LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t cui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(cui_Chart1, cui_Chart1_series_1, cui_Chart1_series_1_array);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CHART1_NUM);
    children[UI_COMP_CHART1_CHART1] = cui_Chart1;
    lv_obj_add_event_cb(cui_Chart1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Chart1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Chart1_create_hook(cui_Chart1);
    return cui_Chart1;
}

