// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: BME_280_Chart

#include "ui.h"

uint8_t slider_change_value =	0;

void slider_change(lv_event_t * e)
{
	slider_change_value = 1;
}
