// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: BME_280_Chart

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Labeltemp = NULL;
lv_obj_t * ui_Labelhum = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_chart_series_t * ui_Chart1_series_1 = NULL;
lv_chart_series_t * ui_Chart1_series_2 = NULL;
// event funtions
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_change(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 694);
    lv_obj_set_height(ui_Chart1, 336);
    lv_obj_set_x(ui_Chart1, -4);
    lv_obj_set_y(ui_Chart1, 32);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 50);
    lv_chart_set_div_line_count(ui_Chart1, 25, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 25, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 5, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 5, true, 50);
    ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xF80707),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x2D07FA),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_2_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);
    lv_obj_set_style_border_side(ui_Chart1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labeltemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labeltemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeltemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeltemp, -270);
    lv_obj_set_y(ui_Labeltemp, -170);
    lv_obj_set_align(ui_Labeltemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeltemp, "Temperature:");
    lv_obj_set_style_text_color(ui_Labeltemp, lv_color_hex(0xF90404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeltemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeltemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelhum = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelhum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelhum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelhum, 247);
    lv_obj_set_y(ui_Labelhum, -170);
    lv_obj_set_align(ui_Labelhum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelhum, "Humidity:");
    lv_obj_set_style_text_color(ui_Labelhum, lv_color_hex(0x042CF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelhum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelhum, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 614);
    lv_obj_set_height(ui_Slider1, 19);
    lv_obj_set_x(ui_Slider1, -9);
    lv_obj_set_y(ui_Slider1, -211);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Chart1 = NULL;
    ui_Labeltemp = NULL;
    ui_Labelhum = NULL;
    ui_Slider1 = NULL;

}
